// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCApCNLHGG9dmI6MdcaZ5TZJjMWCgtdgNo',
    appId: '1:1043321667298:android:81e08858376a36ac7268bb',
    messagingSenderId: '1043321667298',
    projectId: 'smart-car-parking-stystem',
    storageBucket: 'smart-car-parking-stystem.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC0pBQ01V7c3-g6ffc5fSjHLXXAWbHfOo0',
    appId: '1:1045733954182:ios:31bb4414a78b0597d9f707',
    messagingSenderId: '1045733954182',
    projectId: 'carparking-644d2',
    storageBucket: 'carparking-644d2.appspot.com',
    iosBundleId: 'com.example.carParkingSystem',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyA1LPDBxStiZIWjAAE0hgbPYhy2PcCMjoc',
    appId: '1:1045733954182:web:ba0c1d494a02789ad9f707',
    messagingSenderId: '1045733954182',
    projectId: 'carparking-644d2',
    authDomain: 'carparking-644d2.firebaseapp.com',
    storageBucket: 'carparking-644d2.appspot.com',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC0pBQ01V7c3-g6ffc5fSjHLXXAWbHfOo0',
    appId: '1:1045733954182:ios:31bb4414a78b0597d9f707',
    messagingSenderId: '1045733954182',
    projectId: 'carparking-644d2',
    storageBucket: 'carparking-644d2.appspot.com',
    iosBundleId: 'com.example.carParkingSystem',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyA1LPDBxStiZIWjAAE0hgbPYhy2PcCMjoc',
    appId: '1:1045733954182:web:e16303b9720a27f2d9f707',
    messagingSenderId: '1045733954182',
    projectId: 'carparking-644d2',
    authDomain: 'carparking-644d2.firebaseapp.com',
    storageBucket: 'carparking-644d2.appspot.com',
  );

}